name: test fluxion-go

# This will be expanded for more robust testing
# right now we build and run the main test command
# and test the package "types" directory

on:
  pull_request: []
  workflow_dispatch:

  # Bindings should always be checked against the latest containers
  # 2:10 every Thursday
  schedule:
    - cron:  '10 2 * * 4'  

jobs:
  test:
    name: Test fluxion-go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # container base and lib prefix
        test: [["fluxrm/flux-sched:noble", "/usr/lib"],
               ["fluxrm/flux-sched:fedora40", "/usr/lib64"],
               ["fluxrm/flux-sched:bookworm-amd64", "/usr/lib"],
               ["fluxrm/flux-sched:el9", "/usr/lib64"]]

    container:
      image: ${{ matrix.test[0] }}
      options: --user root
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.22

    - name: flux-sched build
      run: git clone https://github.com/flux-framework/flux-sched /opt/flux-sched
#    - name: build flux-sched
#      run: |
#        here=$(pwd)
#        cd /opt/flux-sched
#        mkdir build && cd build && cmake ../ && make -j && sudo make install
#        cd $here
    - name: Test
      run: LIB_PREFIX=${{ matrix.test[1] }} make test-v
