name: test fluxion-go

# This will be expanded for more robust testing
# right now we build and run the main test command
# and test the package "types" directory

on:
  pull_request: []
  workflow_dispatch:

  # Bindings should always be checked against the latest containers
  # 2:10 every Thursday
  schedule:
    - cron:  '10 2 * * 4'  

jobs:
  test:
    name: Test fluxion-go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # container base and lib prefix
        test: [["fluxrm/flux-sched:jammy", "/usr/lib"],
               ["fluxrm/flux-sched:fedora38", "/usr/lib64"],
               ["fluxrm/flux-sched:bookworm-amd64", "/usr/lib"],
               ["fluxrm/flux-sched:el8", "/usr/lib64"]]

    container:
      image: ${{ matrix.test[0] }}
      options: --user root
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    # TODO: we should consider distributing the header files with the release builds
    - name: flux-sched build
      run: git clone https://github.com/flux-framework/flux-sched /opt/flux-sched    
    - name: Build
      run: LIB_PREFIX=${{ matrix.test[1] }} make build
    - name: Test Binary
      run: LIB_PREFIX=${{ matrix.test[1] }} make test-binary
    - name: Test Modules
      run: make test-modules
